const redirects = require("./redirects.json")
const fs = require('fs')
const path = require('path')

exports.onPostBuild = async () => {
  // Generate _redirects file in public/ directory
  // Netlify reads this file after build is complete
  const redirectLines = redirects.map(redirect => {
    const status = redirect.isPermanent ? 301 : 302;
    const force = redirect.force ? '!' : '';
    return `${redirect.fromPath}  ${redirect.toPath}  ${status}${force}`;
  });

  const redirectsContent = `# Redirects for Ośrodek Medicus
# Generated by gatsby-node.js

${redirectLines.join('\n')}
`;

  const publicDir = path.join(__dirname, 'public');
  fs.writeFileSync(path.join(publicDir, '_redirects'), redirectsContent);
  console.log(`✓ Generated _redirects file with ${redirects.length} redirects`);
};